/* ORGANIZANDO FISICAMENTE E LOGICAMENTE UM BANCO DE DADOS

1 - CRIAR UM BANCO COM ARQUIVOS PARA OS SETORES DE MARKETING E VENDAS
2 - CRIAR UM ARQUIVO GERAL (QUEM NÃO É MKT OU VENDAS)
3 - DEIXAR O MDF APENAS COM O DICIONÁRIO DE DADOS
4 - CRIAR 2 GRUPOS DE ARQUIVOS

*/

USE EMPRESA
GO

CREATE TABLE TB_EMPRESA(
	id INT,
	nome VARCHAR(50)
)
GO
