/* AUTO RELACIONAMENTO */
SHOW DATABASES;

CREATE DATABASE AUTORELACIONAMENTO;

USE AUTORELACIONAMENTO;

CREATE TABLE CURSOS(
	IDCURSOS INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	HORAS INT,
	VALOR FLOAT(10, 2),
	ID_PREREQ INT
);

ALTER TABLE CURSOS ADD CONSTRAINT FK_PREREQ
FOREIGN KEY (ID_PREREQ) REFERENCES CURSOS(IDCURSOS);

INSERT INTO CURSOS VALUES (NULL, 'BD RELACIONAL', 20, 400.0, NULL);
INSERT INTO CURSOS VALUES (NULL, 'BUSINESS INTELIGENCE', 40, 800.00, 1); -- PRE-REQUISITO O CURSO DE BD RELACIONAL (POR ISSO O 1 NO FINAL) --
INSERT INTO CURSOS VALUES (NULL, 'RELATORIOS AVANCADOS', 20, 600.00, 2); -- PRE-REQUISITO O CURSO DE BI (POR ISSO O 2 NO FINAL) --
INSERT INTO CURSOS VALUES (NULL, 'LOGICA DE PROGRAMACAO', 20, 400.00, NULL); -- SEM PRE-REQUISITOS --
INSERT INTO CURSOS VALUES (NULL, 'RUBY', 30, 500.00, 4); -- PRE-REQUISITO O CURSO DE LOGICA DE PROGRAMACAO (POR ISSO O 4 NO FINAL) --

SELECT * FROM CURSOS;

SELECT NOME, VALOR, HORAS, IFNULL(ID_PREREQ, "SEM REQUISITO") REQUISITO
FROM CURSOS; 

SELECT 
C.NOME AS CURSO, 
C.VALOR AS VALOR, 
C.HORAS AS CARGA, 
IFNULL(P.NOME, "---") AS PREREQ
FROM CURSOS C
LEFT JOIN CURSOS P
ON P.IDCURSOS = C.ID_PREREQ;
