-- CURSORES --
CREATE DATABASE CURSORES;

USE CURSORES;

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT
);

INSERT INTO VENDEDORES VALUES (NULL, "MARCIA", 52632, 54123, 51356);
INSERT INTO VENDEDORES VALUES (NULL, "CLARA", 52365, 59526, 56432);
INSERT INTO VENDEDORES VALUES (NULL, "JOAO", 57985, 53256, 50235);
INSERT INTO VENDEDORES VALUES (NULL, "LILIAN", 54365, 52636, 51258);
INSERT INTO VENDEDORES VALUES (NULL, "ANTONIO", 52069, 59856, 56985);
INSERT INTO VENDEDORES VALUES (NULL, "GLORIA", 50263, 58956, 53265);

SELECT * FROM VENDEDORES;

SELECT NOME, (JAN + FEV + MAR) AS TOTAL FROM VENDEDORES;

SELECT NOME, TRUNCATE((JAN + FEV + MAR) / 30, 2) AS MEDIA FROM VENDEDORES;

-- INSERINDO TODOS OS DADOS DA TABELA VENDEDORES JUNTO COM O TOTAL E MDIA DE VENDAS --
CREATE TABLE VEND_TOTAL(
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT,
	TOTAL INT,
	MEDIA INT
);

DELIMITER $

CREATE PROCEDURE INSEREDADOS()
BEGIN
	DECLARE FIM INT DEFAULT 0;
	DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT;
	DECLARE VNOME VARCHAR(50);

	DECLARE REG CURSOR FOR(
			SELECT NOME, JAN, FEV, MAR FROM VENDEDORES
		);

	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;

	OPEN REG;

	REPEAT

		FETCH REG INTO VNOME, VAR1, VAR2, VAR3;
		IF NOT FIM THEN

			SET VTOTAL = VAR1 + VAR2 + VAR3;
			SET VMEDIA = VTOTAL / 3;

			INSERT INTO VEND_TOTAL VALUES (VNOME, VAR1, VAR2, VAR3, VTOTAL, VMEDIA);
		END IF;

	UNTIL FIM END REPEAT;

	CLOSE REG;
END
$

DELIMITER ;

SELECT * FROM VENDEDORES;

SELECT * FROM VEND_TOTAL; -- VAZIA --

-- RODANDO O CURSOR --
CALL INSEREDADOS();

SELECT * FROM VEND_TOTAL;
