/* STORAGE PROCEDURE */
CREATE TABLE PESSOA(
	IDPESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK(SEXO IN('M','F')),
	NASCIMENTO DATE NOT NULL
)
GO

CREATE TABLE TELEFONE_PESSOA(
	IDTELEFONE INT NOT NULL IDENTITY,
	TIPO CHAR(3) NOT NULL CHECK(TIPO IN('CEL','COM')),
	NUMERO CHAR(10) NOT NULL,
	ID_PESSOA INT
)
GO

ALTER TABLE TELEFONE_PESSOA ADD CONSTRAINT FK_TELEFONE_PESSOA
FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
ON DELETE CASCADE
GO

INSERT INTO PESSOA VALUES('ANTONIO','M','1981-02-13')
INSERT INTO PESSOA VALUES('DANIEL','M','1985-03-18')
INSERT INTO PESSOA VALUES('CLEIDE','F','1979-10-13')
GO

INSERT INTO TELEFONE_PESSOA VALUES('CEL','9879008',1)
INSERT INTO TELEFONE_PESSOA VALUES('COM','8757909',1)
INSERT INTO TELEFONE_PESSOA VALUES('CEL','9875890',2)
INSERT INTO TELEFONE_PESSOA VALUES('CEL','9347689',2)
INSERT INTO TELEFONE_PESSOA VALUES('COM','2998689',3)
INSERT INTO TELEFONE_PESSOA VALUES('COM','2098978',2)
INSERT INTO TELEFONE_PESSOA VALUES('CEL','9008679',3)
GO

/* CRIANDO A PROCEDURE */
CREATE PROC SOMA
AS
	SELECT 10 + 10 AS 'SOMA'
GO

/* EXECUTANDO */
EXEC SOMA
GO

/* DINAMICAS - COM PARAMETROS */
CREATE PROC CONTA @NUM1 INT,@NUM2 INT
AS
	SELECT @NUM1 + @NUM2
GO

EXEC CONTA 2, 90
GO
-- @ -> VARIAVEL LOCAL
-- @@ -> VARIAVEL GLOBAL

/* APAGANDO PROCEDURE */
DROP PROC CONTA
GO

CREATE PROC CONTA @NUM1 INT,@NUM2 INT
AS
	SELECT (@NUM1 * @NUM2)/@NUM2 AS 'RESULTADO'
GO

EXEC CONTA 10,10
GO

/* PROCEDURES EM TABELAS */
SELECT NOME, NUMERO
FROM PESSOA
INNER JOIN TELEFONE_PESSOA 
ON IDPESSOA = ID_PESSOA
WHERE TIPO = 'CEL'
GO

CREATE PROC TELEFONES @TIPO CHAR(3)
AS
	SELECT NOME, NUMERO
	FROM PESSOA
	INNER JOIN TELEFONE_PESSOA
	ON IDPESSOA = ID_PESSOA
	WHERE TIPO = @TIPO
GO

EXEC TELEFONES 'CEL'
GO

EXEC TELEFONES 'COM'
GO

/* PARAMETROS DE OUTPUT */
SELECT TIPO, COUNT(*) AS 'QUANTIDADE'
FROM TELEFONE_PESSOA
GROUP BY TIPO
GO

/* CRIANDO PROCEDURE COM PARAMETRO DE ENTRADA E SAIDA */
CREATE PROC GETTIPO @TIPO CHAR (3),@CONTADOR INT OUTPUT
AS
	SELECT @CONTADOR = COUNT(*)
	FROM TELEFONE_PESSOA
	WHERE TIPO = @TIPO
	GO

DECLARE @SAIDA INT
EXEC GETTIPO @TIPO = 'CEL',@CONTADOR = @SAIDA OUTPUT
SELECT @SAIDA
GO

-- PROCEDURE COMO REGRA DE NEGOCIO --
/* INSERINDO DADOS EM DUAS TABELAS AO MESMO TEMPO 
PESSOA E TELEFONE_PESSOA
*/
INSERT INTO PESSOA VALUES('MAFRA','M','1981-02-13')
GO

SELECT @@IDENTITY -- GUARDA O ÚLTIMO IDENTITY INSERIDO NA SEÇÃO --
GO

SELECT * FROM PESSOA
GO

CREATE PROC CADASTRO @NOME VARCHAR(30),@SEXO CHAR(1),@NASCIMENTO DATE,
@TIPO CHAR(3),@NUMERO VARCHAR(10)
AS
	DECLARE @FK INT

	INSERT INTO PESSOA VALUES(@NOME,@SEXO,@NASCIMENTO)-- GEREI UM ID --

	SET @FK = (SELECT IDPESSOA FROM PESSOA WHERE IDPESSOA
	= @@IDENTITY)

	INSERT INTO TELEFONE_PESSOA VALUES(@TIPO,@NUMERO,@FK)
GO

-- EXECUTANDO --
CADASTRO 'JORGE','M','1981-01-01','CEL','97856985'
GO

-- NÃO USE ESSA QUERY, SÓ PARA FINS DIDÁTICOS --
SELECT PESSOA.*,TELEFONE_PESSOA.*
FROM PESSOA
INNER JOIN TELEFONE_PESSOA
ON IDPESSOA = ID_PESSOA
GO 
