/* BÁSICO DE TSQL */
/* TSQL É UM BLOCO DE LINGUAGEM DE PROGRAMAÇÃO 
TEMOS BLOCOS NOMEADOS E BLOCOS ANONIMOS

PROGRAMAS SÃO UNIDADES QUE PODEM SER CHAMADAS DE BLOCO

ANONIMOS -> BLOCOS ANONIMOS NÃO RECEBEM NOME, PORQUE
NÃO SÃO SALVOS NO BANCO. CRIAMOS BLOCOS ANONIMOS QUANDO
IREMOS EXECUTÁ-LOS UMA SÓ VEZ OU TESTAR ALGO
*/


-- bloco de execução --
BEGIN
	PRINT 'PRIMEIRO BLOCO'
END
GO

-- bloco de atribuição de variáveis --
DECLARE
	@CONTADOR INT
BEGIN
	SET @CONTADOR = 5
	PRINT @CONTADOR
END
GO

/* NO SQL SERVER CADA COLUNA, VARIAVEL LOCAL, EXPRESSÃO E
PARAMETRO TEM UM TIPO */
DECLARE
	@V_NUMERO NUMERIC(10,2) = 100.52,
	@V_DATA DATETIME = '20170207'
BEGIN
	PRINT 'VALOR NUMERICO: ' + CAST(@V_NUMERO AS VARCHAR)
	PRINT 'VALOR NUMERICO: ' + CONVERT(VARCHAR,@V_NUMERO)
	PRINT 'VALOR DE DATA: ' + CAST(@V_DATA AS VARCHAR) -- VEJA A DIFERENCA
	PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR,@V_DATA,121) -- ''
	PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR,@V_DATA,105) -- ''
END
GO

-- CAST E CONVERT FAZEM A MESMA COISA, MAS CONVERT É USADO MAIS EM DATA --

/* ATRIBUINDO RESULTADOS À VARIAVEIS */
CREATE TABLE CARROS(
	CARRO VARCHAR(20),
	FABRICANTE VARCHAR(30)
)
GO

INSERT INTO CARROS VALUES('KA','FORD')
INSERT INTO CARROS VALUES('FIESTA','FORD')
INSERT INTO CARROS VALUES('PRIMA','CHEVROLET')
INSERT INTO CARROS VALUES('CLIO','RENAULT')
INSERT INTO CARROS VALUES('SANDERO','RENAULT')
INSERT INTO CARROS VALUES('CHEVETTE','CHEVROLET')
INSERT INTO CARROS VALUES('OMEGA','CHEVROLET')
INSERT INTO CARROS VALUES('PALIO','FIAT')
INSERT INTO CARROS VALUES('DOBLO','FIAT')
INSERT INTO CARROS VALUES('UNO','FIAT')
INSERT INTO CARROS VALUES('GOL','VOLKSWAGEN')
GO

SELECT * FROM CARROS
GO

DECLARE
	@V_CONT_FORD INT,
	@V_CONT_FIAT INT

BEGIN
	-- METODO 1 - O SELECT PRECISA RETORNAR UMA SIMPLES COLUNA E UM SO RESULTADO --
	SET @V_CONT_FORD = (SELECT COUNT(*) FROM CARROS
	WHERE FABRICANTE = 'FORD')

	PRINT 'QUANTIDADE FORD: ' + CAST(@V_CONT_FORD AS VARCHAR)

	-- METODO 2 --
	SELECT @V_CONT_FIAT = COUNT(*) FROM CARROS WHERE FABRICANTE = 'FIAT'

	PRINT 'QUANTIDADE FIAT: ' + CONVERT(VARCHAR,@V_CONT_FIAT)
END
GO

/* CONDICIONAIS -> IF E ELSE */
DECLARE
	@NUMERO INT = 5
BEGIN
	IF @NUMERO = 5
		PRINT 'O VALOR É VERDADEIRO'
	ELSE
		PRINT 'O VALOR É FALSO'
END
GO

/* CONDICIONAL CASE */
-- O CASE REPRESENTA UMA COLUNA --
DECLARE
	@CONTADOR INT
BEGIN
	SELECT 
	CASE
		WHEN FABRICANTE = 'FIAT' THEN 'FAIXA 1'
		WHEN FABRICANTE = 'CHEVROLET' THEN 'FAIXA 2'
		ELSE 'FAIXA 3'
	END AS "INFORMACOES",
	*
	FROM CARROS
END
GO

/* LOOPS COM WHILE*/
DECLARE
	@I INT = 1
BEGIN
	WHILE (@I < 15)
	BEGIN
		PRINT 'VALOR DE @I = ' + CAST(@I AS VARCHAR) 
		SET @I += 1
	END
END
GO
